with CTE as (
select 

TO_TIMESTAMP(STARTED_AT) STARTED_AT,
DATE( TO_TIMESTAMP(STARTED_AT) ) DATE_STARTED_AT,
HOUR( TO_TIMESTAMP(STARTED_AT) ) HOUR_STARTED_AT,

CASE WHEN DAYNAME( TO_TIMESTAMP(STARTED_AT) ) IN ('Sat' , 'Sun')
THEN 'WEEKEND' 
ELSE 'BUSINESSDAY'
END DAY_TYPE,

CASE WHEN MONTH( TO_TIMESTAMP(STARTED_AT) ) IN (12,1,2)
 THEN 'WINTER'
 WHEN MONTH( TO_TIMESTAMP(STARTED_AT) ) IN (12,1,2)
 THEN 'SPRING'
 WHEN MONTH( TO_TIMESTAMP(STARTED_AT) ) IN (3,4,5)
 THEN 'SUMMER'
 ELSE 'AUTUMN'
 END STATION_OF_YEAR

FROM 
{{ source('demo' , 'bike') }}
)

select * from CTE